INSERT INTO room_count_range(title, min_count, max_count) VALUES('0~30번', 0, 30);
INSERT INTO room_count_range(title, min_count, max_count) VALUES('31~60번', 31, 60);
INSERT INTO room_count_range(title, min_count, max_count) VALUES('61~99번', 61, 99);
INSERT INTO room_count_range(title, min_count, max_count) VALUES('100~150번', 100, 150);
INSERT INTO room_count_range(title, min_count, max_count) VALUES('151~200번', 151, 200);
INSERT INTO room_count_range(title, min_count, max_count) VALUES('201~300번', 201, 300);
INSERT INTO room_count_range(title, min_count, max_count) VALUES('301번 이상', 301, 99999);

INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '액션', '', '', '🏍', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '범죄', '', '', '🚨', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', 'SF', '', '', '👽', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '코미디', '', '', '😄', '', FALSE, 3);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '로맨스', '', '', '❤️', '', FALSE, 4);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '스릴러', '', '', '🔪', '', FALSE, 5);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '공포', '', '', '👻', '', FALSE, 6);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '판타지', '', '', '🧙', '', FALSE, 7);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '추리', '', '', '🔎', '', FALSE, 8);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '드라마', '', '', '🔎', '', FALSE, 9);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '미스터리', '', '', '🫢', '', FALSE, 10);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '감성', '', '', '😂', '', FALSE, 11);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '어드벤처', '', '', '🧩', '', FALSE, 12);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '역사', '', '', '😂', '', FALSE, 13);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '동화', '', '', '😂', '', FALSE, 14);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '탈옥', '', '', '⛓️', '', FALSE, 15);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '잠입', '', '', '🕶', '', FALSE, 16);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '야외', '', '', '🏃‍♀️', '', FALSE, 17);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('PREFERRED_GENRE', '문제방', '', '', '🧬', '', FALSE, 18);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '관찰력', '', '', '🔎', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '분석력', '', '', '📊', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '추리력', '', '', '🔎', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '집중력', '', '', '✨', '', FALSE, 3);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '순발력', '', '', '🤸‍♂️', '', FALSE, 4);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '실행력', '', '', '🙌', '', FALSE, 5);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '창의력', '', '', '💡', '', FALSE, 6);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '침착함', '', '', '🧘‍♀️', '', FALSE, 7);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('USER_STRENGTH', '협업 능력', '', '', '🤝', '', FALSE, 8);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_IMPORTANT_FACTOR', '탄탄한 스토리', '스토리', '', '📒', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_IMPORTANT_FACTOR', '다양한 연출', '연출', '', '✨', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_IMPORTANT_FACTOR', '명확한 개연성', '개연성', '', '✏️', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_IMPORTANT_FACTOR', '퀄리티 높은 인테리어', '인테리어', '', '🚪', '', FALSE, 3);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_IMPORTANT_FACTOR', '커다란 스케일', '스케일', '', '🔥', '', FALSE, 4);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_IMPORTANT_FACTOR', '신선한 문제', '신선한 문제', '', '🎁', '', FALSE, 5);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_IMPORTANT_FACTOR', '논리적인 문제', '논리적인 문제', '', '📊', '', FALSE, 6);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HORROR_THEME_POSITION', '극쫄', '', '사소한 거에도 놀랄 정도로 겁이 많아요', '😇', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HORROR_THEME_POSITION', '쫄', '', '겁이 많은 편이에요', '😰', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HORROR_THEME_POSITION', '변쫄', '', '무서워하지만, 공포 테마는 좋아요', '🫥', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HORROR_THEME_POSITION', '마지모탱', '', '무서워하지만, 쫄들 사이에서 탱 포지션이에요', '🛡', '', FALSE, 3);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HORROR_THEME_POSITION', '탱', '', '무서워하지 않아요', '🛡', '', FALSE, 4);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HORROR_THEME_POSITION', '극탱', '', '공포를 오히려 즐겨요', '🛡', '', FALSE, 5);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HORROR_THEME_POSITION', '잘 모르겠어요', '', '혹은 공포 테마 경험이 없어요', '', '', FALSE, 6);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HINT_USAGE_PREFERENCE', '힌트 안써요', '', '막히더라도 사용하지 않아요', '', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HINT_USAGE_PREFERENCE', '최소한의 힌트만', '', '시간이 오래 걸릴 때만 써요', '', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('HINT_USAGE_PREFERENCE', '힌트 사용 괜찮아요', '', '조금만 막혀도 바로 사용해요', '', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('DEVICE_LOCK_PREFERENCE', '장치', '', '특정 물체를 조작, 작동하여 진행되는 방식\n(센서, 기계 등)', '⚙️', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('DEVICE_LOCK_PREFERENCE', '자물쇠', '', '문제를 풀어 얻는 답 (숫자, 문자, 방향 등)이나\n열쇠로 자물쇠를 푸는 방식', '🔒', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('DEVICE_LOCK_PREFERENCE', '장치&자물쇠 모두', '', '', '', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('ACTIVITY', '높은 활동성', '', '걷고, 뛰고, 계단 이동하는 게 좋아요', '', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('ACTIVITY', '중간 활동성', '', '땀나지 않을 정도로 적당히 움직이는 게 좋아요', '', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('ACTIVITY', '낮은 활동성', '', '걷는 정도가 좋아요', '', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('ACTIVITY', '활동성 최소', '', '최소한의 이동만 있는 게 좋아요', '', '', FALSE, 3);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '이과형 문제', '', '', '', '', FALSE, 0);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '노가다 문제', '', '', '', '', FALSE, 1);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '긴 지문', '', '', '', '', FALSE, 2);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '삑딱쿵', '', '', '', '', FALSE, 3);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '낮은 조도', '', '', '', '', FALSE, 4);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '높은 난이도', '', '', '', '', FALSE, 5);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '문제방', '', '', '', '', FALSE, 6);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '억지 감동', '', '', '', '', FALSE, 7);
INSERT INTO element(type, title, sub_title, description, emoji, image_url, is_deleted, priority) VALUES('THEME_DISLIKED_FACTOR', '억지 활동성', '', '', '', '', FALSE, 8);

INSERT INTO color(title, mode, shape, direction, start_color, end_color, is_deleted, priority) VALUES('Gradient Red', 'GRADIENT', 'LINEAR', 'TOP_LEFT_TO_BOTTOM_RIGHT', '#FF453C', '#FFACB3', FALSE, 0);
INSERT INTO color(title, mode, shape, direction, start_color, end_color, is_deleted, priority) VALUES('Gradient Pink', 'GRADIENT', 'LINEAR', 'TOP_LEFT_TO_BOTTOM_RIGHT', '#FF60BF', '#FFACB3', FALSE, 1);
INSERT INTO color(title, mode, shape, direction, start_color, end_color, is_deleted, priority) VALUES('Gradient Green', 'GRADIENT', 'LINEAR', 'TOP_LEFT_TO_BOTTOM_RIGHT', '#ADF695', '#42AC5D', FALSE, 2);
INSERT INTO color(title, mode, shape, direction, start_color, end_color, is_deleted, priority) VALUES('Gradient Blue', 'GRADIENT', 'LINEAR', 'TOP_TO_BOTTOM', '#81A2EB', '#4EC1E6', FALSE, 3);
INSERT INTO color(title, mode, shape, direction, start_color, end_color, is_deleted, priority) VALUES('Gradient Purple', 'GRADIENT', 'LINEAR', 'TOP_LEFT_TO_BOTTOM_RIGHT', '#2E2E8D', '#73549D', FALSE, 4);
INSERT INTO color(title, mode, shape, direction, start_color, end_color, is_deleted, priority) VALUES('Solid Black', 'SOLID', 'NONE', 'NONE', '#000000', '#000000', FALSE, 5);
